name: Deploy Pages and Notify Client

on:
  workflow_run:
    workflows: ["Generate PDF"]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy_pages:
      uses: ./.github/workflows/static.yml
      with:
        publish_dir: '.'  # Adjust if necessary
  
  notify_client:
    needs: deploy_pages
    runs-on: ubuntu-latest
    steps:
      - name: Notify Client
        env:
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        run: |
          PAYLOAD=$(jq -n --arg timestamp "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" '{
            status: "success",
            message: "PDF generated successfully",
            timestamp: $timestamp
          }')
          SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$WEBHOOK_SECRET" | awk '{print $2}')
          SIGNATURE="sha256=$SIGNATURE"
          echo "Signature: $SIGNATURE"
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-hub-signature-256: $SIGNATURE" \
            -d "$PAYLOAD" \
            "${{ secrets.PDF_WEBHOOK_URL }}"
