name: Generate PDF

on:
  workflow_run:
    workflows: ["Deploy Pages and Notify Client"]
    types: [completed]
jobs: 
  generate_pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate PDF
        run: node generatePDF.js

      - name: Commit and push PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add menu.pdf
          git commit -m "Update generated PDF" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  deploy:
    needs: generate_pdf
   # Call your reusable static deployment workflow as a job to deploy your JSON
    uses: ./.github/workflows/static.yml
    with:
      publish_dir: '.'  # Adjust if your site builds to a specific folder
