name: Generate PDF

on:
  push:
    branches:
      - main  # Change to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:  # Set permissions for the GITHUB_TOKEN
      contents: write  # Allow the action to write to the repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Update to v3
        with:
          node-version: '20'  # Use Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Generate PDF
        run: node generatePDF.js  # Run your PDF generation script

      - name: Commit and push PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output.pdf
          git commit -m "Update generated PDF"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
