name: Generate PDF

on:
  push:
    branches:
      - main  # Change to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:  # Set permissions for the GITHUB_TOKEN
      contents: write  # Allow the action to write to the repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Update to v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Update to v3
        with:
          node-version: '20'  # Use Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Generate PDF
        run: node generatePDF.js  # Run your PDF generation script

      - name: Commit and push PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add menu.pdf
          git commit -m "Update generated PDF" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Client
        env:
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        run: |
          # Create the JSON payload
          PAYLOAD=$(jq -n --arg timestamp "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" '{
            status: "success",
            message: "PDF generated successfully",
            timestamp: $timestamp
          }')
    
          # Compute the HMAC-SHA256 signature using the secret
          SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "$WEBHOOK_SECRET" | awk '{print $2}')
          SIGNATURE="sha256=$SIGNATURE"
          
          echo "Signature: $SIGNATURE"
          
          # Send the POST request with the computed signature
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-hub-signature-256: $SIGNATURE" \
            -d "$PAYLOAD" \
            "${{ secrets.PDF_WEBHOOK_URL }}"
